# schema: ${NEXT_PUBLIC_GRAPHQL_API_ENDPOINT}
schema: https://vl.vrikshatech.in/api/public/graphql
documents: ./src/framework/graphql/**/*.graphql
plugins:
  - typescript-operations
  - typescript-react-apollo
cacheDir: __generated__
