# schema: ${NEXT_PUBLIC_GRAPHQL_API_ENDPOINT}
schema: http://localhost:8000/graphql
documents: ./src/framework/graphql/**/*.graphql
plugins:
  - typescript-operations
  - typescript-react-apollo
cacheDir: __generated__
